# Generated by Django 4.0.10 on 2024-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='password',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
