# Generated by Django 4.0.10 on 2024-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_email_remove_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_recruiting',
            field=models.BooleanField(default=False),
        ),
    ]
